name: 'Publish Binary'
description: 'Publish Binary to GitHub Releases and Cloudflare R2'
inputs:
  os:
    description: "Operating system"
    required: true
  target:
    description: "Release target"
    required: true
  version:
    description: "Release version"
    required: true
runs:
  using: "composite"
  steps:

    - name: Pack binary
      id: package
      shell: bash
      run: |
        mkdir -p dist
        case ${{ inputs.os }} in
          linux)
            tar -czf dist/bigsql-${{ inputs.target }}.tar.gz -C target/${{ inputs.target }}/release bigsql
            echo "file=bigsql-${{ inputs.target }}.tar.gz" >> $GITHUB_OUTPUT
            ;;
          macos)
            tar -czf dist/bigsql-${{ inputs.target }}.tar.gz -C target/${{ inputs.target }}/release bigsql
            echo "file=bigsql-${{ inputs.target }}.tar.gz" >> $GITHUB_OUTPUT
            ;;
          windows)
            7z a -tzip dist/bigsql-${{ inputs.target }}.zip target/${{ inputs.target }}/release/bigsql.exe
            echo "file=bigsql-${{ inputs.target }}.zip" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Unsupported OS: ${{ inputs.os }}"
            exit 1
            ;;
        esac

    - name: Publish to Github Releases
      id: name
      shell: bash
      run: |
        gh release upload ${{ inputs.version }} dist/${{ steps.package.outputs.file }} --clobber

    - name: Upload package to Cloudflare R2
      id: upload
      shell: bash
      run: |
        aws s3 cp dist/${{ steps.package.outputs.file }} s3://repo/bigsql/${{ inputs.version }}/${{ steps.package.outputs.file }} --no-progress
